
# Dependencies
plugins: [jekyll-paginate] 

# Setup
title: Empiah Analysis
tagline: 'welcome to Empiah Analysis'
description: 'welcome to Empiah Analysis'
baseurl: 
url: 'https://empiah.github.io'


author:
  name:           'Empiah'
  url:            'https://twitter.com/EmpiahCapital'


# Custom vars
version:          2.1.0

github:
  repo:           'https://github.com/Empiah'


  #Structure
  paginate:         5

