
# Dependencies
plugins: [jekyll-paginate] 

# Permalinks
permalink:        pretty

# Setup
title: Empiah Analysis
tagline: 'welcome to Empiah Analysis'
description: 'welcome to Empiah Analysis'
url: 'https://empiah.github.io'
baseurl:  /

author:
  name:           'Empiah'
  url:            'https://twitter.com/EmpiahCapital'

#Structure
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           'https://github.com/Empiah'


