
# Setup
title: Empiah Analysis
tagline: 'welcome to Empiah Analysis'
description: 'welcome to Empiah Analysis'
baseurl: "" 
url: https://empiahanalysis.com 

#twitter_username: EmpiahCapital
#github_username:  Empiah
#email: Get in touch via twitter @EmpiahCapital
#name: Empiah Analysis

author:
  name:           'Empiah'
  url:            https://twitter.com/EmpiahCapital

  paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Empiah

# Dependencies
plugins: [jekyll-paginate]
excerpt_separator: <!--more-->
markdown:         redcarpet
highlighter:      pygments


